blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """Создание модели для блога в таблице БД"""

    title = models.CharField(max_length=150, verbose_name='заголовок')
    description = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    creation_date = models.DateTimeField(verbose_name='дата публикации')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}, {self.description}, {self.views_count}'

    class Meta:
        """Представление написания заголовков блога в админке"""

        verbose_name = "блог"
        verbose_name_plural = "статьи"

blog/views.py
from django.views.generic import ListView, DetailView

from blog.models import Blog
from blog.services import get_blog_cache


class BlogListView(ListView):
    """Контроллер блога для просмотра списка статей"""

    model = Blog

    def get_context_data(self, **kwargs):
        context = {
            'blog_list': get_blog_cache()
        }

        return context


class BlogDetailView(DetailView):
    """Контроллер блога для детального просмотра статьи"""

    model = Blog

    def get_object(self, queryset=None):
        """Создаем счетчик просмотров"""

        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <br>
    <h2 align="center">{{ blog.title }}</h2><br><br>
    <div class="row mx-2">
        <div class="col-md-4 mb-3">
            {% load media_tags %}
            <img src="{% mediapath blog.preview %}" class="img-fluid" alt="{{ blog.title }}">
        </div>
        <div class="col-md-8 mb-3">
            <p>{{ blog.description }}</p><br><br>
            <div class="card-footer">
                Количество просмотров статьи: {{ blog.views_count }}
                <br><br>
                <a align="center " href="{% url 'blog:blog_list' %}"
                   class="button">Назад к списку статей</a>
            </div>
        </div>
    </div><br>
{% endblock %} 

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div>
        <div class="row mt-2">
            <div class="col m-2"><br>
                <h2 align="center">Статьи блога</h2>
                <br><br>
                <table class="table table-reflow">
                    <thead>
                    <tr class="table-active">
                        <th>№</th>
                        <th>Дата публикации</th>
                        <th>Просмотры</th>
                        <th>Заголовок</th>
                        <th>Прочитать</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for blog in blog_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ blog.creation_date }}</td>
                            <td>{{ blog.views_count }}</td>
                            <td>{{ blog.title }}</td>
                            <td>
                                <div class="btn-group">
                                    <a href="{% url 'blog:blog_view' blog.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Прочитать статью</a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}