blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, MessageCreateView, MessageListView, MessageDetailView, MessageUpdateView, \
    MessageDelete, IndexView, MailingCreateView, ClientCreateView, MailingListView, ClientDetailView, ClientUpdateView, \
    ClientDelete, MailingDetailView, MailingUpdateView, MailingDelete, LogListView, MailingUpdateManagerView, \
    MailingSendMessageView

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),

    path('clients/create_client/', ClientCreateView.as_view(), name='create_client'),
    path('clients/clients_list/', ClientListView.as_view(), name='clients_list'),
    path('clients/view_client/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('clients/edit_client/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('clients/delete_client/<int:pk>/', ClientDelete.as_view(), name='delete_client'),

    path('messages/create_message/', MessageCreateView.as_view(), name='create_message'),
    path('messages/messages_list/', MessageListView.as_view(), name='messages_list'),
    path('messages/view_message/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('messages/edit_message/<int:pk>/', MessageUpdateView.as_view(), name='edit_message'),
    path('messages/delete_message/<int:pk>/', MessageDelete.as_view(), name='delete_message'),

    path('mailings/create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailings/mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/view_mailing/<int:pk>/', MailingDetailView.as_view(), name='view_mailing'),
    path('mailings/edit_mailing_manager/<int:pk>/', MailingUpdateManagerView.as_view(), name='edit_mailing_manager'),
    path('mailings/manager_edit_mailing/<int:pk>/', MailingUpdateManagerView.as_view(), name='manager_edit_mailing'),
    path('mailings/delete_mailing/<int:pk>/', MailingDelete.as_view(), name='delete_mailing'),
    path('mailings/send_mailing/<int:pk>/', MailingSendMessageView.as_view(), name='send_mailing'),

    path('log/log_list/', LogListView.as_view(), name='log_list'),
]

users/urls.py
from django.urls import path
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, set_new_password, \
    UserConfirmEmailView, UserConfirmedView, password_reset, UserConfirmationSentView, UserListView, UserUpdateManagerView

app_name = "users"

urlpatterns = [

    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registration/", RegisterView.as_view(), name="registration"),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("profile/set_password", set_new_password, name="set_password"),
    path('password_reset/', password_reset, name='password_reset'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('edit_user/<int:pk>/', UserUpdateManagerView.as_view(), name='edit_user'),
]

main/forms.py
from django import forms

from main.models import Mailing, Client, Message


class StyleFormMixin:
    """Класс-миксин для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_active":
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    """Класс для генерации формы создания рассылки"""

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop('owner', None)
        super().__init__(*args, **kwargs)
        # Добавляем поле с клиентами из модели клиентов и фильтруем только своих клиентов
        self.fields['clients'].queryset = self.fields['clients'].queryset.filter(owner=owner)
        # Добавляем поле с сообщениями из модели сообщений и фильтруем только свои сообщения
        self.fields['message'].queryset = Message.objects.filter(owner=owner)
        # Предлагаем к показу выбора только тему сообщения
        choices = [(message.id, message.message_subject) for message in self.fields['message'].queryset]
        self.fields['message'].widget = forms.Select(
            choices=[('', '--------')] + choices,  # Добавляем пустой элемент в список выбора
            attrs={'class': 'form-control'}
        )

    class Meta:
        model = Mailing
        exclude = ('owner', 'last_sent')


class MailingUpdateManagerForm(StyleFormMixin, forms.ModelForm):
    """Форма у рассылки для менеджеров-модераторов сервиса"""

    class Meta:
        model = Mailing
        fields = ["is_active"]


class ClientForm(StyleFormMixin, forms.ModelForm):
    """Класс для генерации формы создания клиентов-получателей рассылки"""

    class Meta:
        model = Client
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    """Класс для генерации формы рассылочного сообщения"""

    class Meta:
        model = Message
        exclude = ('owner',)

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin

import random
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView

from blog.models import Blog
from main.forms import MailingForm, ClientForm, MessageForm, MailingUpdateManagerForm
from main.models import Client, Message, Mailing, Log



class IndexView(TemplateView):
    """Класс отображения главной страницы сервиса"""

    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'

        # Получение количества рассылок всего
        total_mailings = Mailing.objects.count()
        context['total_mailings'] = total_mailings

        # Получение количества активных рассылок
        active_mailings = Mailing.objects.filter(is_active=True).count()
        context['active_mailings'] = active_mailings

        # Получение количества уникальных клиентов для рассылок
        unique_clients = Client.objects.count()
        context['unique_clients'] = unique_clients

        # Получение всех статей блога
        all_blogs = list(Blog.objects.all())

        if len(all_blogs) >= 3:
            # Получение трёх случайных статей из блога
            random_blogs = random.sample(all_blogs, 3)
        else:
            # Если количество статей меньше 3, выводим все статьи
            random_blogs = all_blogs

        context['random_blogs'] = random_blogs

        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания нового клиента - получателя рассылки"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:clients_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра списка клиентов"""

    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('main.can_manager_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """Контроллер для детального просмотра клиента"""

    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования клиента"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:clients_list')


class ClientDelete(LoginRequiredMixin, DeleteView):
    """Контроллер для удаления клиента"""

    model = Client
    success_url = reverse_lazy('main:clients_list')


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания нового сообщения"""

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:messages_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра списка сообщений"""

    model = Message

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('main.can_manager_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Контроллер для детального просмотра сообщения"""

    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования сообщения"""

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:messages_list')


class MessageDelete(LoginRequiredMixin, DeleteView):
    """Контроллер для удаления сообщения"""

    model = Message
    success_url = reverse_lazy('main:messages_list')


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания новой рассылки"""

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра списка рассылок"""

    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('main.can_manager_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class MailingSendMessageView(LoginRequiredMixin, DetailView):
    """Контроллер для старта рассылки"""

    template_name = 'main/mailing_send_message_successful.html'
    model = Mailing

    def get(self, *args, **kwargs):
        mailing = self.get_object()
        mailing.send()
        return super().get(*args, **kwargs)


class MailingDetailView(DetailView):
    """Контроллер для детального просмотра рассылки"""

    model = Mailing


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования рассылки"""

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs


class MailingUpdateManagerView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования рассылки менеджером-модератором"""

    template_name = 'main/mailing_manager_form.html'
    model = Mailing
    form_class = MailingUpdateManagerForm
    success_url = reverse_lazy('main:mailing_list')


class MailingDelete(LoginRequiredMixin, DeleteView):
    """Контроллер для удаления рассылки"""

    model = Mailing
    success_url = reverse_lazy('main:mailing_list')


class LogListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра списка логов рассылок"""

    model = Log

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('main.can_manager_view'):
            return queryset
        return queryset.filter(mailing__owner=self.request.user)

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>СУР</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'main/includes/inc_menu.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md text-center">
                Сервис управления рассылками
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
    <br>
    <h2 align="center">Удаление клиента</h2>
    <div class="container">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "<b>{{ client.client_name }}</b>"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'main:clients_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
            <br>
            <a href="{% url 'main:clients_list' %}"
               class="button">Назад к списку клиентов</a>
        </div>
    </div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <br>
    <h2 align="center">Просмотр клиента</h2><br><br>
    <div class="row mx-2">
        <div class="col-md-4 mb-3">
        </div>
        <div class="col-md-8 mb-3">
            <p><b>Имя:</b> {{ client.client_name }}</p>
            <p><b>Email:</b> {{ client.client_email }}</p>
            <p><b>Комментарий:</b><br>{{ client.comment }}</p><br>
            <a href="{% url 'main:clients_list' %}"
               class="button">Назад к списку клиентов</a>
        </div>
    </div><br><br>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content %}
    <br>
    <h2 align="center">
        {% if client %}
            Редактировать клиента
        {% else %}
            Создать нового клиента
        {% endif %}
    </h2><br><br>
    <div class="col-md-10 mx-auto">
        <div class="row"><br>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if client %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                        <br>
                        <a align="center " href="{% url 'main:clients_list' %}"
                           class="button">Назад к списку клиентов</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<div>
    <div class="row mt-2">
        <div class="col m-2"><br>
            {% if not perms.main.can_manager_view %}
            <h2 align="center">Список ваших клиентов</h2>
            <br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="{% url 'main:create_client' %}">Добавить нового
                        клиента</a>
                </div>
            </div>
            {% else %}
            <h2 align="center">Клиенты всех пользователей</h2>
            <br>
            {% endif %}
            {% if client_list %}
            <br>
            <table class="table">
                <thead>
                <tr class="table-active">
                    <th>№</th>
                    <th>Имя клиента</th>
                    <th>Email клиента</th>
                    <th>Комментарий</th>
                    <th>Действия с клиентом</th>
                </tr>
                </thead>
                <tbody>
                {% for client in client_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ client.client_name }}</td>
                    <td>{{ client.client_email }}</td>
                    <td>{{ client.comment }}</td>
                    <td>
                        <div class="btn-group">
                                        <a href="{% url 'main:view_client' client.pk %}"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                            {% if not perms.main.can_manager_view %}
                            <a href="{% url 'main:edit_client' client.pk %}"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'main:delete_client' client.pk %}"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}<br>
            <p align="center">Вы еще ничего не создавали</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12 text-center">
    {% if not perms.main.can_manager_view %}
    <h1 class="mt-4 mb-5">Добро пожаловать на наш сайт сервиса управления рассылками!</h1>
    <img src="media/home.png" alt="заставка">
    <p></p>
    <p>Наш сервис поможет быстро создавать рассылки, задавать им параметры, а также просматривать
        результаты этих рассылок.</p>
    <p>Мы стремимся сделать наш сайт максимально удобным и понятным для вас, чтобы вы могли легко использовать его для
        своих нужд.</p>
    <h3>Просто попробуй!</h3>
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'main:mailing_list' %}">Создать рассылку</a>
    {% else %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войдите для создания рассылки</a>
    {% endif %}
    {% else %}
    <div class="container mt-5">
        <h2 align="center">Вы вошли с правами менеджера, вам недоступны некоторые функции сервиса!</h2>
        {% endif %}
    </div>
    <br><br><br>
    <p>
        Всего рассылок на нашем сервисе: {{ total_mailings }}<br>
        Количество активных рассылок: {{ active_mailings }}<br>
        Количество уникальных клиентов для рассылок: {{ unique_clients }}<br>
    </p><br>
    <h4>Статьи нашего блога</h4>
    <ul>
        {% for blog in random_blogs %}
        <li>
            <a href="{% url 'blog:blog_view' blog.pk %}">{{ blog.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
</div><br>
</div>
{% endblock %}

main/templates/main/log_list.html
{% extends 'main/base.html' %}
{% block content %}
<div>
    <div class="row mt-2">
        <div class="col m-2"><br>
            <h2 align="center">Список логов рассылки</h2>
            {% if log_list %}
            <br>
            <br>
            <table class="table">
                <thead>
                <tr class="table-active">
                    <th>№</th>
                    <th>Рассылка</th>
                    <th>Время старта</th>
                    <th>Время последней попытки</th>
                    <th>Период</th>
                    <th>Статус попытки</th>
                    <th>Результат</th>
                </tr>
                </thead>
                <tbody>
                {% for log in log_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ log.mailing.message.message_subject }}</td>
                    <td>{{ log.mailing.start_time }}</td>
                    <td>{{ log.last_attempt }}</td>
                    <td>{{ log.mailing.frequency }}</td>
                    {% if log.status == 'success' %}
                    <td class="text-success">{{ log.status }}</td>
                    {% elif log.status == 'failed' %}
                    <td class="text-danger">{{ log.status }}</td>
                    {% endif %}
                    <td>{{ log.message|safe }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}<br>
            <p align="center">Еще не было запущено ни одной рассылки</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <br>
    <h2 align="center">Просмотр рассылки</h2><br><br>
    <div class="row mx-2">
        <table class="table table-reflow">
            <thead>
            <tr class="table-active">
                <th>Начало</th>
                <th>Окончание</th>
                <th>Период</th>
                <th>Статус</th>
                <th>Сообщение</th>
                <th>Клиенты</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ mailing.start_time }}</td>
                <td>{{ mailing.completion_time }}</td>
                <td>{{ mailing.frequency }}</td>
                <td>{{ mailing.status }}</td>
                <td>{{ mailing.message.message_subject }}</td>
                <td>
                    {% for client in object.clients.all|slice:":3" %}
                        {{ client }}<br>
                    {% endfor %}
                </td>
            </tr>
            </tbody>
        </table>
        <a href="{% url 'main:mailing_list' %}"
           class="button">Назад к списку рассылок</a>
    </div>
    </div><br><br>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}
{% block content %}
<div>
    <div class="row mt-2">
        <div class="col m-2"><br>
            {% if not perms.main.can_manager_view %}
            <h2 align="center">Все ваши рассылки</h2>
            <p align="center">Начните сооздавать вашу первую рассылку с создания нового привлекательного
                сообщения
                и добавления списка получателей</p><br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="{% url 'main:create_mailing' %}">Добавить
                        рассылку</a>
                    <a class="btn btn-outline-primary" href="{% url 'main:create_message' %}">Добавить
                        сообщение</a>
                    <a class="btn btn-outline-primary" href="{% url 'main:create_client' %}">Добавить
                        клиента</a>
                </div>
            </div>
            {% else %}
            <h2 align="center">Рассылки всех пользователей</h2>
            <br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="{% url 'users:users_list' %}">Список всех
                        пользователей</a>
                </div>
            </div>
            {% endif %}
            {% if mailing_list %}
            <br>
            <table class="table table-reflow">
                <thead>
                <tr class="table-active">
                    <th>№</th>
                    <th>Сообщение</th>
                    <th>Начало</th>
                    <th>Окончание</th>
                    <th>Период</th>
                    <th>Статус</th>
                    <th>Клиенты</th>
                    <th>Действия с рассылками</th>
                </tr>
                </thead>
                <tbody>
                {% for mailing in mailing_list %}
                <tr class="{% if mailing.status == 'created' %}bg-warning
                                   {% elif mailing.status == 'started' %}bg-success
                                   {% elif mailing.status == 'completed' %}bg-danger
                                   {% endif %}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ mailing.message.message_subject }}</td>
                    <td>{{ mailing.start_time }}</td>
                    <td>{{ mailing.completion_time }}</td>
                    <td>{{ mailing.frequency }}</td>
                    {% if mailing.get_status == 'created' %}
                    <td class="text-black-50">{{ mailing.get_status }}</td>
                    {% elif mailing.get_status == 'started' %}
                    <td class="text-primary">{{ mailing.get_status }}</td>
                    {% elif mailing.get_status == 'completed' %}
                    <td class="text-success">{{ mailing.get_status }}</td>
                    {% endif %}
                    <td>
                        {% for client in mailing.clients.all %}
                        {{ client.client_email }}<br>
                        {% endfor %}
                    </td>
                    <td>
                        {% if not perms.main.can_manager_view %}
                        <div class="btn-group">
                            {% if mailing.get_status == 'created' %}
                            <a href="{% url 'main:send_mailing' mailing.pk %}"
                               class="btn btn-sm btn-outline-warning">Отправить</a>
                            {% endif %}
                            <a href="{% url 'main:view_mailing' mailing.pk %}"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                            <a href="{% url 'main:edit_mailing' mailing.pk %}"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'main:delete_mailing' mailing.pk %}"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                            {% else %}
                            <div class="btn-group">
                                <a href="{% url 'main:view_mailing' mailing.pk %}"
                                   class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                {% if mailing.is_active %}
                                <a href="{% url 'mail:edit_mailing_manager' mailing.pk %}"
                                   class="btn btn-sm btn-outline-danger">Деактивировать</a>
                                {% else %}
                                <a href="{% url 'mail:edit_mailing_manager' mailing.pk %}"
                                   class="btn btn-sm btn-outline-success">Активировать</a>
                                {% endif %}
                                <a href="{% url 'users:edit_user' mailing.owner.pk %}"
                                   class="btn btn-sm btn-outline-primary">Пользователь</a>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}<br>
            <p align="center">Вы еще ничего не создавали</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %} 

main/templates/main/mailing_send_message_successful.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="container mt-5">
        <br><br>
        <h4 align="center">
            Рассылка была успешно отправлена!<br>
            Посмотреть рузультаты отправки вы можете в <a href="{% url 'main:log_list' %}">логах</a>.
        </h4>
        <br>
    </div>
{% endblock %} 

main/templates/main/message_list.html
{% extends 'main/base.html' %}
{% block content %}
<div>
    <div class="row mt-2">
        <div class="col m-2"><br>
            {% if not perms.main.can_manager_view %}
            <h2 align="center">Список ваших сообщений для рассылки</h2>
            <br>
            <div class="row mt-2">
                <div class="col m-2">
                    <a class="btn btn-outline-primary" href="{% url 'main:create_message' %}">Добавить новое
                        сообщение</a>
                </div>
            </div>
            {% else %}
            <h2 align="center">Сообщения всех пользователей</h2>
            <br>
            {% endif %}
            {% if message_list %}
            <br>
            <table class="table">
                <thead>
                <tr class="table-active">
                    <th>№</th>
                    <th>Тема сообщения</th>
                    <th>Текст сообщения</th>
                    <th>Действия с сообщением</th>
                </tr>
                </thead>
                <tbody>
                {% for message in message_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ message.message_subject }}</td>
                    <td>{{ message.message_text|slice:":120" }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'main:view_message' message.pk %}"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                            {% if not perms.main.can_manager_view %}
                            <a href="{% url 'main:edit_message' message.pk %}"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'main:delete_message' message.pk %}"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}<br>
            <p align="center">Вы еще ничего не создавали</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %} 